server{
	# Listen on port 443 with SSL (HTTPS)
	# http2 enables HTTP/2 for better performance
	listen	443 ssl;
	listen	[::]:443 ssl;

	# Your domain name - reads from environment variable
	server_name aychikhi.42.fr;

	# --- TLS Configuration ---
	# Path to our self-signed certificate and key
	ssl_certificate	/etc/ssl/certs/nginx.crt;
	ssl_certificate_key /etc/ssl/private/nginx.key;

	# Only allow TLSv1.2 and TLSv1.3 - subject requirement
	ssl_protocols	TLSv1.2 TLSv1.3;

	# Strong cipher suites for security
	ssl_ciphers	HIGH:!aNULL:!MD5;

	# --- WordPress Root ---
	# This is where WordPress files lives inside the container
	# (mounted from out wordpress volume)
	root /var/www/wordpress;

	# Default fie to serve
	index index.php index.html;

	# --- Request Hangling ---
	location / {
		# Try to serve the file directly
		# If not found, pass to index.php
		try_files $uri $uri/ /index.php?$args;
	}
	
	# --- PHP Handling ---
	# Any .php file gets passed to WordPress container via FastCGI
	location ~ \.php$ {
		# Don't process files that don't exist
		try_files $uri =404;

		# Split the path into script and path info
		fastcgi_split_path_info ^(.+\.php)(/.+)$;

		# Pass to WordPress container on port 9000
		# "wordpress" is the sevice name in docker-compose
		# Docker resolves this name to the container's IP automatically 
		fastcgi_pass wordpress:9000;

		fastcgi_index index.php;

		# Include standard FastCGI parameters
		include fastcgi_params;

		# Include standard FastCGI parameters
		include fastcgi_params;

		# Tell PHP where the script is
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
} 
